[book]
title = "從零開始學 Rust"
authors = ["Andy Shiue"]
language = "zh-TW"

[rust]
edition = "2024"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/AndyShiue/rust-book"
edit-url-template = "https://github.com/AndyShiue/rust-book/edit/main/{path}"
site-url = "https://andyshiue.github.io/rust-book/"

[output.html.playground]
editable = true

[output.html.print]
page-break = false